on:
  push:
    branches:
      - prod
      
jobs:
  Create-Release:
    runs-on: ubuntu-latest
    steps:
      - uses: ncipollo/release-action@v1
        with:
          tag: "0.0.3"
          generateReleaseNotes: "true"
          
