on:
  push:
    branches:
      - prod
      
jobs:
  Create-Release:
    runs-on: ubuntu-latest
    steps:
      - uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.event.head_commit.id }}
          generateReleaseNotes: "true"
          
