name: PR Test Trigger
on:
  pull_request:
    types: [labeled]

jobs:
  filter-labels:
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.filter.outputs.pull_request }}

    steps:
      - id: filter
        run: |
          LABEL=$(cat $GITHUB_EVENT_PATH |jq -r '.pull_request.labels[] | select(.name == "Ready for Test").name')
          echo "Label: $LABEL"
          if [ "$LABEL" != "Ready for Test" ]; then
            echo "this PR is not labeled for testing"
            exit 0
          fi
          echo "this PR is ready for test"

          IN_TEST=$(curl "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/issues?labels=Deployed%20to%20Test")
          if [ "$(echo $IN_TEST | jq '. | length')" != "0" ]; then
            echo "test is busy right now"
            exit 0
          fi
          echo "test is available"
          echo "::set-output name=pull_request::$(cat $GITHUB_EVENT_PATH |jq -r '.pull_request.number')"

  put-pr-in-test:
    runs-on: ubuntu-latest
    needs: filter-labels
    if: needs.filter-issues.outputs.pr-number
    steps:
      - run: |
          echo "pr-number: ${{ inputs.pr-number }}"
          curl "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/issues/${{ inputs.pr-number }}/labels" -d '{"labels":["Deployed to Test"]}' -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
