name: PR Test Trigger
on:
  issues:
    types: [ opened ]

jobs:
  
  filter-issues:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "$GITHUB_EVENT_PATH"
          cat "$GITHUB_EVENT_PATH"
          LABEL=$(cat $GITHUB_EVENT_PATH |jq '.issue.labels[] | select(.name == "Testing").name')
          if [ "$LABEL" = "Testing" ]; then
            echo "this is a test issue"
          else
            echo "this is not a test issue"
          fi

  