name: PR Test Trigger
on:
  pull_request:
    types: [labeled]

jobs:
  filter-labels:
    runs-on: ubuntu-latest

    steps:
      - id: filter
        run: |
          cat $GITHUB_EVENT_PATH
          LABEL=$(jq -r '.pull_request.labels[] | select(.name == "Ready for Test").name' $GITHUB_EVENT_PATH)
          echo "Label: $LABEL"
          if [ "$LABEL" != "Ready for Test" ]; then
            echo "this PR is not labeled for testing"
            exit 0
          fi
          echo "this PR is ready for test"

          IN_TEST=$(curl "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/issues?labels=Deployed%20to%20Test" -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}')
          if [ "$(echo $IN_TEST | jq '. | length')" != "0" ]; then
            echo "test is busy right now"
            exit 0
          fi
          echo "test is available"
          PR_NUMBER=$(cat $GITHUB_EVENT_PATH |jq -r '.pull_request.number')

          curl "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/labels" -d '{"labels":["Deployed to Test"]}' -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
