name: PR Test Trigger
on:
  pull_request:
    types: [labeled]

jobs:
  filter-labels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: filter
        run: |
          LABEL=$(jq -r '.pull_request.labels[] | select(.name == "Ready for Test").name' $GITHUB_EVENT_PATH)
          echo "Label: $LABEL"
          if [ "$LABEL" != "Ready for Test" ]; then
            echo "this PR is not labeled for testing"
            exit 0
          fi
          echo "this PR is ready for test"

          IN_TEST=$(curl "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/issues?labels=Deployed%20to%20Test" -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}')
          if [ "$(echo $IN_TEST | jq '. | length')" != "0" ]; then
            echo "test is busy right now"
            exit 0
          fi
          echo "test is available"
          ISSUE_NUMBER=$(jq -r '.pull_request.number' $GITHUB_EVENT_PATH)

          echo "issue-number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT

        #############
      - name: deploy
        ############
        uses: ./.github/actions/deploy-to-test
        with:
          issue-number: ${{ steps.filter.outputs.issue-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
