name: PR Test Trigger
on:
  issues:
    types: [ opened ]

jobs:
  
  filter-issues:
    runs-on: ubuntu-latest

    steps:
      - run: |
          LABEL=$(cat $GITHUB_EVENT_PATH |jq -r '.issue.labels[] | select(.name == "Testing").name')
          echo "Label: $LABEL"
          if [ "$LABEL" -eq "Testing" ]; then
            echo "this is a test issue"
          else
            echo "this is not a test issue"
          fi

  