name: Production Release
on:
  workflow_dispatch:

jobs:
  release-to-production:
    name: https://github.com/dhuyvett/releases/compare/prod...main
    runs-on: ubuntu-latest
    environment: 
      name: prod
      
    steps:
      #####################
      - name: checkout prod
        ###################
        uses: actions/checkout@v3
        with:
          ref: prod

      ####################################
      - name: update prod branch from main
        ##################################
        id: update-prod
        run: |
          # this will fail if main and prod diverge
          git pull origin main
          git push
          echo "::set-output name=TARGET_COMMIT::$(git rev-parse --verify HEAD)"

      #################################
      - name: create release with notes
        ###############################
        uses: ./.github/actions/create-release
        with:
          base-version: "1.0"
          target-commitish: ${{ steps.update-prod.outputs.TARGET_COMMIT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
